
    create table CantidadPorHora (
        obs_por_hora_id bigint generated by default as identity (start with 1),
        cantidadBusquedasPorHora varbinary(255),
        primary key (obs_por_hora_id)
    )

    create table Condicion (
        NOMBRE_CONDICION varchar(31) not null,
        condicion_id bigint generated by default as identity (start with 1),
        primary key (condicion_id)
    )

    create table GrupoDeUsuarios (
        grupo_id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (grupo_id)
    )

    create table GrupoDeUsuarios_Recetas (
        GrupoDeUsuarios_grupo_id bigint not null,
        recetasGrupales_receta_id bigint not null
    )

    create table GrupoDeUsuarios_Usuario (
        GrupoDeUsuarios_grupo_id bigint not null,
        usuarios_usuario_id bigint not null
    )

    create table MasBuscada (
        obs_mas_buscada_id bigint generated by default as identity (start with 1),
        recetasBuscadas blob(255),
        primary key (obs_mas_buscada_id)
    )

    create table PorSexo (
        obs_por_sexo_id bigint generated by default as identity (start with 1),
        busquedasDeHombres blob(255),
        busquedasDeMujeres blob(255),
        primary key (obs_por_sexo_id)
    )

    create table Recetas (
        TIPO_RECETA varchar(31) not null,
        receta_id bigint generated by default as identity (start with 1),
        calorias integer not null,
        dificultadPreparacion varchar(255),
        explicacionPasos varbinary(255),
        favorita boolean not null,
        nombre varchar(255),
        publica boolean not null,
        temporada varchar(255),
        primary key (receta_id)
    )

    create table Recetas_Condicion (
        Recetas_receta_id bigint not null,
        condiciones_condicion_id bigint not null
    )

    create table Recetas_Recetas (
        Recetas_receta_id bigint not null,
        subrecetas_receta_id bigint not null
    )

    create table Usuario (
        usuario_id bigint generated by default as identity (start with 1),
        altura double not null,
        disgustos varbinary(255),
        nacimiento varbinary(255),
        nombre varchar(255),
        peso double not null,
        preferencias varbinary(255),
        rutina varchar(255),
        sexo integer,
        primary key (usuario_id)
    )

    create table Usuario_Condicion (
        Usuario_usuario_id bigint not null,
        condiciones_condicion_id bigint not null
    )

    create table Usuario_GrupoDeUsuarios (
        Usuario_usuario_id bigint not null,
        grupos_grupo_id bigint not null
    )

    create table Usuario_Recetas (
        Usuario_usuario_id bigint not null,
        recetas_receta_id bigint not null
    )

    create table VeganosQueBuscanDificiles (
        obs_veganos_dificiles_id bigint generated by default as identity (start with 1),
        primary key (obs_veganos_dificiles_id)
    )

    create table VeganosQueBuscanDificiles_Usuario (
        VeganosQueBuscanDificiles_obs_veganos_dificiles_id bigint not null,
        veganosQueBuscaronRecetasDificiles_usuario_id bigint not null
    )

    alter table GrupoDeUsuarios_Recetas 
        add constraint UK_7n4cd19a5m85eangexe7yj59x  unique (recetasGrupales_receta_id)

    alter table Recetas_Condicion 
        add constraint UK_2kqghgt7wm17iljxwd556gqdt  unique (condiciones_condicion_id)

    alter table Usuario_Condicion 
        add constraint UK_hf8wjg5qfkkq2471s9nnjt6ev  unique (condiciones_condicion_id)

    alter table VeganosQueBuscanDificiles_Usuario 
        add constraint UK_jcs3u6uo4uomhwxhyttjhga2q  unique (veganosQueBuscaronRecetasDificiles_usuario_id)

    alter table GrupoDeUsuarios_Recetas 
        add constraint FK_7n4cd19a5m85eangexe7yj59x 
        foreign key (recetasGrupales_receta_id) 
        references Recetas

    alter table GrupoDeUsuarios_Recetas 
        add constraint FK_jqeywql3i4o2fl4p3t0yn6qlj 
        foreign key (GrupoDeUsuarios_grupo_id) 
        references GrupoDeUsuarios

    alter table GrupoDeUsuarios_Usuario 
        add constraint FK_n4gcwto1updokq6mq3r4fest1 
        foreign key (usuarios_usuario_id) 
        references Usuario

    alter table GrupoDeUsuarios_Usuario 
        add constraint FK_f1n985l2ryxci67dc2x927l8i 
        foreign key (GrupoDeUsuarios_grupo_id) 
        references GrupoDeUsuarios

    alter table Recetas_Condicion 
        add constraint FK_2kqghgt7wm17iljxwd556gqdt 
        foreign key (condiciones_condicion_id) 
        references Condicion

    alter table Recetas_Condicion 
        add constraint FK_foas5xn44qaxyhrsjvwcnw12s 
        foreign key (Recetas_receta_id) 
        references Recetas

    alter table Recetas_Recetas 
        add constraint FK_fg9su1lr8mrn50vhf9iu7ev12 
        foreign key (subrecetas_receta_id) 
        references Recetas

    alter table Recetas_Recetas 
        add constraint FK_k6m807bis5ln5go1nqhbttmrp 
        foreign key (Recetas_receta_id) 
        references Recetas

    alter table Usuario_Condicion 
        add constraint FK_hf8wjg5qfkkq2471s9nnjt6ev 
        foreign key (condiciones_condicion_id) 
        references Condicion

    alter table Usuario_Condicion 
        add constraint FK_89d8qqsdt4igd11msx33wqns1 
        foreign key (Usuario_usuario_id) 
        references Usuario

    alter table Usuario_GrupoDeUsuarios 
        add constraint FK_q4w55wmvq9jp5b480ce1mww7f 
        foreign key (grupos_grupo_id) 
        references GrupoDeUsuarios

    alter table Usuario_GrupoDeUsuarios 
        add constraint FK_piakopvu9q8fwriuy7atv5nl7 
        foreign key (Usuario_usuario_id) 
        references Usuario

    alter table Usuario_Recetas 
        add constraint FK_c5tmxw8tl5w0ajhcx7rt1o0kp 
        foreign key (recetas_receta_id) 
        references Recetas

    alter table Usuario_Recetas 
        add constraint FK_oha3mp6bq893qdahu67h7y38y 
        foreign key (Usuario_usuario_id) 
        references Usuario

    alter table VeganosQueBuscanDificiles_Usuario 
        add constraint FK_jcs3u6uo4uomhwxhyttjhga2q 
        foreign key (veganosQueBuscaronRecetasDificiles_usuario_id) 
        references Usuario

    alter table VeganosQueBuscanDificiles_Usuario 
        add constraint FK_i8p37eji2r5hxi1qyrn5ydhh8 
        foreign key (VeganosQueBuscanDificiles_obs_veganos_dificiles_id) 
        references VeganosQueBuscanDificiles
